// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.mingluck.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 2;</code>
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 2;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();
}
