// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountQry.proto

package com.mzsg.demo.grpc.qryaccount;

public interface AccountQryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:accountService.AccountQryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *请求流水
   * </pre>
   *
   * <code>string requestId = 1;</code>
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   *请求流水
   * </pre>
   *
   * <code>string requestId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   *用户ID
   * </pre>
   *
   * <code>string userId = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <pre>
   *用户ID
   * </pre>
   *
   * <code>string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
