// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountQry.proto

package com.mzsg.demo.grpc.qryaccount;

public final class QryAccountProto {
  private QryAccountProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accountService_AccountQryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accountService_AccountQryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accountService_AccountQryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accountService_AccountQryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020AccountQry.proto\022\016accountService\"6\n\021Ac" +
      "countQryRequest\022\021\n\trequestId\030\001 \001(\t\022\016\n\006us" +
      "erId\030\002 \001(\t\"P\n\022AccountQryResponse\022\021\n\trequ" +
      "estId\030\001 \001(\t\022\n\n\002rc\030\002 \001(\005\022\013\n\003msg\030\003 \001(\t\022\016\n\006" +
      "amount\030\004 \001(\0052a\n\021QryAccountService\022L\n\003Qry" +
      "\022!.accountService.AccountQryRequest\032\".ac" +
      "countService.AccountQryResponseB2\n\035com.m" +
      "zsg.demo.grpc.qryaccountB\017QryAccountProt" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_accountService_AccountQryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_accountService_AccountQryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accountService_AccountQryRequest_descriptor,
        new java.lang.String[] { "RequestId", "UserId", });
    internal_static_accountService_AccountQryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_accountService_AccountQryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accountService_AccountQryResponse_descriptor,
        new java.lang.String[] { "RequestId", "Rc", "Msg", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
