// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestModel.proto

package com.test.grpc.service.model;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.grpc.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
