// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestModel.proto

package com.test.grpc.service.model;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.grpc.TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
