// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestService.proto

package com.test.grpc.service;

public final class TestService {
  private TestService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TestService.proto\022\rcom.test.grpc\032\017Test" +
      "Model.proto2U\n\016TestRpcService\022C\n\010sayHell" +
      "o\022\032.com.test.grpc.TestRequest\032\033.com.test" +
      ".grpc.TestResponseB\031\n\025com.test.grpc.serv" +
      "iceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.test.grpc.service.model.TestModel.getDescriptor(),
        }, assigner);
    com.test.grpc.service.model.TestModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
